### ISSUE TITLE
Add `len()` to Mime?

### ISSUE THREAD

**Issue by teotwaki** [notgull/mr-mime#2]
I've [added](https://github.com/notgull/mr-mime/compare/master...teotwaki:mr-mime:add-len) `.len()` to `Mime` in order to accurately calculate the Content-Length header of an HTTP query in an embedded environment which contains a couple of MIME types. I'm also trying to do so without allocating or writing out the MIME type to a buffer to calculate its length (hence why I'm expending a few CPU cycles to calculate the length).

Would you be interested in adding this to mr-mime, and should I create a PR for it? Interested to hear your thoughts.

**Comment by notgull** [comment]
I would accept this PR!
